global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          service: 'rentastech-backend'
          environment: 'development'

